apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: match-logs-pvc
  namespace: workshop
  labels:
    app: match-event-logger
    component: storage
spec:
  accessModes:
    - ReadWriteOnce  # Single node access (good for k3s single-node)
    # For multi-node clusters, use ReadWriteMany with NFS or similar
  resources:
    requests:
      storage: 1Gi  # 1GB for match event logs
  # storageClassName: local-path  # k3s default storage class
  # Uncomment and adjust based on your cluster's storage class
