apiVersion: v1
kind: Service
metadata:
  name: {{ include "stats-aggregator.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "stats-aggregator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "stats-aggregator.selectorLabels" . | nindent 4 }}