apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-scheduler
  namespace: workshop
  labels:
    app: match-scheduler
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-scheduler
  template:
    metadata:
      labels:
        app: match-scheduler
        tier: backend
    spec:
      containers:
      - name: match-scheduler
        image: ghcr.io/thorstensen/forte-k8s-workshop/match-scheduler:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        # ConfigMap values
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: match-scheduler-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: match-scheduler-config
              key: NODE_ENV
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: match-scheduler-config
              key: ALLOWED_ORIGINS
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: match-scheduler
  namespace: workshop
  labels:
    app: match-scheduler
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: match-scheduler
