apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-center
  namespace: workshop
  labels:
    app: notification-center
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-center
  template:
    metadata:
      labels:
        app: notification-center
        tier: backend
    spec:
      containers:
      - name: notification-center
        image: ghcr.io/thorstensen/forte-k8s-workshop/notification-center:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-center
  namespace: workshop
  labels:
    app: notification-center
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: notification-center
