apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-aggregator
  namespace: workshop
  labels:
    app: stats-aggregator
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-aggregator
  template:
    metadata:
      labels:
        app: stats-aggregator
        tier: backend
    spec:
      containers:
      - name: stats-aggregator
        image: ghcr.io/thorstensen/forte-k8s-workshop/stats-aggregator:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        # Optional: Mount secret for external API
        - name: EXTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: stats-aggregator-secret
              key: EXTERNAL_API_KEY
              optional: true  # Don't fail if secret doesn't exist
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: stats-aggregator
  namespace: workshop
  labels:
    app: stats-aggregator
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: stats-aggregator
