apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: notificationcenter
  namespace: notificationcenter
  labels:
    app: notificationcenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationcenter
  template:
    metadata:
      labels:
        app: notificationcenter
    spec:
      containers:
      - name: notificationcenter
        image: ghcr.io/thorstensen/forte-k8s-workshop/notification-center:latest
        ports:
        - containerPort: 8080