apiVersion: v2
name: betting-service
description: A Helm chart for Betting Service microservice
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservice
  - betting-service
  - football
  - forte
home: https://github.com/Thorstensen/forte-k8s-workshop
sources:
  - https://github.com/Thorstensen/forte-k8s-workshop
maintainers:
  - name: Tobias Thorstensen
    email: tobias.thorstensen@fortedigital.com